[package]
name = "cross"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bichannel = "0.0.4"
crossbeam = "0.8.2"
crossbeam-channel = "0.5.8"
reqwest = { version = "0.11", features = ["json", "blocking"] }
threadpool = "1.8.1"
serde_json = "1"
scopeguard = "1.1.0"
crossbeam-deque = "0.8.3"
crossbeam-utils = "0.8.15"
uuid = { version = "1.3.2", features = ["v4"] }
backtrace = "0.3.67"
reqwest-middleware = "0.2.2"
task-local-extensions = "0.1.4"
ureq = { version = "2.6.2", features = ["json"] }
