[package]
name = "notion_scraper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
# The name of the native library. This is the name which will be used in Python to import the
# library (i.e. `import notion_rs`). If you change this, you must also change the name of the
# `#[pymodule]` in `src/lib.rs`.
name = "notion_scraper"
# "cdylib" is necessary to produce a shared library for Python to import from.
#
# Downstream Rust code (including code in `bin/`, `examples/`, and `tests/`) will not be able
# to `use notion_rs;` unless the "rlib" or "lib" crate type is also included, e.g.:
# crate-type = ["cdylib", "rlib"]
crate-type = ["cdylib"]

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1"
pyo3 = { version = "0.18", features = ["extension-module"] }
pyo3-asyncio = { version = "0.18", features = ["async-std-runtime"] }
async-std = { version = "1.9", features = ["tokio1"] }
rayon = "1.7.0"
async-recursion = "1.0.4"
futures = "0.3.28"
